### ISSUE TITLE
Parameter mismatch - var state = new User(conditional params); // (at Under murmur project>VirtualServer.cs>UpdateUserState Method)

### ISSUE THREAD

**Issue by jafarulla15** [HarpyWar/murmur-ice-net#3]
I am new and facing one issue at this new User(..) parameter mismatch.
Please need kind help.

![image](https://user-images.githubusercontent.com/15998911/80595341-63818d80-8a46-11ea-9f39-86cdca478cf0.png)

**Comment by HarpyWar** [comment]
Well, to build `Murmur` project you should run `MurmurCompiler` or define required versions in the project properties.
Please, read https://github.com/HarpyWar/murmur-ice-net/issues/2#issuecomment-386875382

First you have to add a reference to `Ice.dll` for `Murmur` project.

**Comment by jafarulla15** [comment]
@HarpyWar Thank you.
I have downloaded and installed from https://yulli.cleanvoice.ru/ for testing. and getting same error.
So, I think I am doing some wrong at murmur server config.

Kindly can you please give me detailed instructions - what I will do at murmur server to enable ice client connection at murmur server.

**Comment by HarpyWar** [comment]
Actually setup for Ice interface is described on https://yulli.cleanvoice.ru at the bottom of the page. PublishedEndpoints is required only if your server has not external IP address in network interfaces.

If you get an error, usually it mean that Ice interface was not setup properly on the server, or wrong Murmur version on a client is selected.

**Comment by jafarulla15** [comment]
@HarpyWar, Thanks a lot. It was my mistake of configuring server.
Thanks for your time.
