### ISSUE TITLE
You are moved to root by the server -- Mumble client

### ISSUE THREAD

**Issue by rezaulk** [HarpyWar/murmur-ice-net#5]
Describe the bug:
I am creating Mumble channel and User buy the Ice in my asp.net core projects.
Initially It works properly like voice communication and message sending.

After working many time, If I moved to another channel that time server moved me to root.
some channel works but many channels don't works
Don't know why it's moved to root

I checked Mumble server DB log... no specific error in logs.

![Screenshot_3](https://user-images.githubusercontent.com/33289815/138859775-7b563a04-0094-490f-9182-32ff2655d3e9.png)

**Comment by HarpyWar** [comment]
Make sure there are no other 3d party scripts connected to Ice which may trigger this move.

If you think the issue in the code, please provide the code example which can be used to reproduce the unwanted behaviour on new server.

**Comment by rezaulk** [comment]
https://github.com/rezaulk/MumbleClient

Can you please check this code?
I uploaded test project. By API calling Channel are created but mumble user/anynomus user not stable on that channel

**Comment by HarpyWar** [comment]
Just comment out implementation for all direct user moves in your code to test it. For instance MoveTochannel method.
I mean that the issue is in your app logic, not in the library.

**Comment by rezaulk** [comment]
@HarpyWar 
Finally solved the issue. 
The issue was logical issue in my backend broker server.
