### ISSUE TITLE
Algorithm negotiation fail

### ISSUE THREAD

**Issue by Oazis79** [HarpyWar/murmur-ice-net#6]
Hello,
Moved mumble server to new VPS with "Debian 11" installed, there was a problem connecting to the server.  Can you advise how to solve the problem?
Thank you.
![image](https://user-images.githubusercontent.com/12032309/173239274-826b76f3-434a-411a-a388-1916e2939f9a.JPG)

**Comment by HarpyWar** [comment]
The issue is not applicable to the library.

Yulli Mur uses outdated SSH library which does not support newest algorithm, details by the link
https://bitbucket.org/HarpyWar/yulli/issues/15/ssh-issues-algorithm-negotiation-fail
You can disable SSH connection to connect Ice directly.
